### ISSUE TITLE
Warnings: Poll aborted, parameters invalid

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica-directory#48] opened 2020-06-21 09:21 UTC
While looking at the 'app.log' I found a lot of warnings about aborted polls. I obfuscated the personal details in the provided example to protect the privacy of the user. I hope it's still useful.

```
WARNING {"uid":"4b22814"}: Poll aborted, parameters invalid. {"params":{"addr":"XXXXXXXX@squeet.me","nick":"XXXXXXXX","guid":"962c3e1011580d55f59b027333704200","key":null,"homepage":"https://squeet.me/profile/XXXXXXXX","comm":false,"account-type":2,"dfrn-request":"https://squeet.me/dfrn_request/XXXXXXXX","dfrn-confirm":"https://squeet.me/dfrn_confirm/XXXXXXXX","dfrn-notify":"https://squeet.me/dfrn_notify/XXXXXXXX","dfrn-poll":"https://squeet.me/dfrn_poll/XXXXXXXX","fn":"Xxxx Xxxx","photo":"https://squeet.me/photo/4142ed67060b534d415c2da9xxxxxxxx-4.jpg?ts=1526641377","tags":"freedom collaboration sharing","language":"en","updated":"2016-10-24T03:35:02+02:00","contacts":4,"last-activity":"2017-10","about":"&quot;freedom ........ asking\nthe question&quot;\nAsk ........ active!","locality":"Xxxxxxxx","country-name":"Xxxxxxxx","_timings":{"fetch":152,"scrape":0}}}
```

**Same log snippet with line breaks for better overview:**

``
WARNING {"uid":"4b22814"}: Poll aborted, parameters invalid. {"params":{"addr":"XXXXXXXX@squeet.me","nick":"XXXXXXXX","guid":"962c3e1011580d55f59b027333704200","key":null,"homepage":"https://squeet.me/profile/XXXXXXXX","comm":false,"account-type":2,"dfrn-request":"https://squeet.me/dfrn_request/XXXXXXXX","dfrn-confirm":"https://squeet.me/dfrn_confirm/XXXXXXXX","dfrn-notify":"https://squeet.me/dfrn_notify/XXXXXXXX","dfrn-poll":"https://squeet.me/dfrn_poll/XXXXXXXX","fn":"Xxxx Xxxx","photo":"https://squeet.me/photo/4142ed67060b534d415c2da9xxxxxxxx-4.jpg?ts=1526641377","tags":"freedom collaboration sharing","language":"en","updated":"2016-10-24T03:35:02+02:00","contacts":4,"last-activity":"2017-10","about":"&quot;freedom ........ asking\nthe question&quot;\nAsk ........ active!","locality":"Xxxxxxxx","country-name":"Xxxxxxxx","_timings":{"fetch":152,"scrape":0}}}
``

Directory 2.3.1 (but showing 2.3.0 at the page footer)
PHP 7.3
MariaDB 10.3
Database schema migrated to version 5

**Comment by realkinetix** [comment] 2020-09-16 04:57
I'm seeing the same thing - piles of them.  

Could it be from "if (empty($params['key'])) { $errors++; }" ?  Key is null/empty in the requests I see.

It looks like it's expected to get a value in the Scrape (src/classes/Utils/Scrape.php)... a section called "Pull out hCard profile elements":

$targets = array('fn', 'pdesc', 'photo', 'key', 'locality', 'region', 'postal-code', 'country-name');

I'm not too sure what is required here though, and why 'key' might be missing during a scrape.

**Comment by MrPetovan** [comment] 2020-09-26 21:09
Duplicate of #45

**Closed as completed by MrPetovan** 2020-09-26 21:09 UTC
Labels: bug
